[package]
name = "abacus"
version = "0.1.0"
edition = "2024"
authors = ["dylanfraser"]
readme = "README.md"

[profile.release]
opt-level = "z"
strip = "symbols"
debug = 0
lto = "thin"
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = true

[profile.dev]
opt-level = 0
incremental = true
codegen-units = 256
lto = false

[dependencies]
rustyline = { version = "15.0", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive", "std", "rc"], optional = true }

[features]
default = ["units", "stats", "distributions", "date", "financial", "repl"]
units = []
stats = []
distributions = []
date = []
financial = []
serde = ["dep:serde"]
repl = ["dep:rustyline"]

[[bin]]
name = "repl"
path = "src/bin/repl.rs"
required-features = ["repl"]

[[bin]]
name = "abacus"
path = "src/main.rs"
